In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices() )

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15301534530923677735
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 2000394651
locality {
  bus_id: 1
  links {
  }
}
incarnation: 16297109994631968461
physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1"
]


In [1]:
%config IPCompleter.greedy=True

In [60]:
from keras.models import Model
from keras.layers import Dense, Dropout, Activation, Input
from keras.layers.merge import _Merge
import keras.backend as K
import numpy as np
from tensorflow.keras.utils import plot_model
import pandas as pd
import tensorflow as tf

In [21]:
quantidade_de_alimentos = 6

In [22]:
# macarrão, pirarucu, banha, ovo cozido, arroz, chocolate

In [23]:
valores_de_certa_comida = np.array([[13,1.5,75], [25, 7, 5], [0, 100, 0], [12.6, 10, 1.2], [2.5, 0.2, 28], [4.8, 30.8, 60]])
valores_de_certa_comida[0] / 100

array([0.13 , 0.015, 0.75 ])

In [87]:
valores_de_certa_comida.shape

(6, 3)

In [49]:
array = np.array([1,1,1,1,1,1], dtype= np.float32)
array = np.reshape(array, (1,quantidade_de_alimentos)) 
array

array([[1., 1., 1., 1., 1., 1.]], dtype=float32)

In [26]:
array.shape

(1, 6)

In [56]:
quantidade_desejada = np.array([160, 138, 530], dtype= np.float32)
quantidade_desejada = np.expand_dims(quantidade_desejada, axis= 0)
quantidade_desejada.shape

(1, 3)

In [13]:
np.zeros(shape= (3))

array([0., 0., 0.])

In [8]:
import os

In [11]:
os.path.isdir('C:/Users/pituc/Downloads/archive (11)')

True

In [17]:
os.path.isfile('C:/Users/pituc/Downloads/archive (11)/nutrition.csv')

True

In [16]:
dataset = pd.read_csv('C:/Users/pituc/Downloads/archive (11)/nutrition.csv') # não se esqueça da porra da terminação .csv

In [62]:
def somando_os_nutrientes_respectivos(quantidade_dos_alimentos):
    soma_dos_nutrientes_totais = np.zeros(shape= (3))
    for n in range(quantidade_dos_alimentos.shape[1]):
        soma_dos_nutrientes_totais = soma_dos_nutrientes_totais + quantidade_dos_alimentos[0][n] * (valores_de_certa_comida[n] / 100)
    #lista_de_soma_dos_nutrientes_totais.append(soma_dos_nutrientes_totais)
    return soma_dos_nutrientes_totais

In [29]:
somando_os_nutrientes_respectivos(array)

array([0.579, 1.495, 1.692])

In [63]:
def multiplicar_K_por_respectivos_valores_valores(y_true, y_pred):
    somas_dos_nutrientes_respectivos = somando_os_nutrientes_respectivos(y_pred)
    return K.square(y_true - somas_dos_nutrientes_respectivos)

In [61]:
tf.config.run_functions_eagerly(True)

In [80]:
quantidade_de_alimentos

6

In [64]:
entrada_gerador = Input(shape= (quantidade_de_alimentos,) ) 
x = entrada_gerador
n_camadas_gerador = 4

for n in range(n_camadas_gerador):
    if n < n_camadas_gerador - 1:
        camada = Dense(units= 15, activation= None)
    else:
        camada = Dense(units= quantidade_de_alimentos, activation= 'relu')
    x = camada(x)

saida_gerador = x
gerador = Model(entrada_gerador, saida_gerador)

In [65]:
gerador.compile(loss= multiplicar_K_por_respectivos_valores_valores, optimizer= 'adam' )

In [75]:
gerador.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 6)]               0         
_________________________________________________________________
dense_16 (Dense)             (None, 15)                105       
_________________________________________________________________
dense_17 (Dense)             (None, 15)                240       
_________________________________________________________________
dense_18 (Dense)             (None, 15)                240       
_________________________________________________________________
dense_19 (Dense)             (None, 6)                 96        
Total params: 681
Trainable params: 681
Non-trainable params: 0
_________________________________________________________________


In [67]:
array

array([[1., 1., 1., 1., 1., 1.]], dtype=float32)

In [68]:
quantidade_desejada

array([[160., 138., 530.]], dtype=float32)

In [69]:
gerador.fit( array , quantidade_desejada , epochs= 2000 )

C:\Users\pituc\anacondabr\envs\p39\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py:4211: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(


Epoch 1/2000
1/1 [==============================] - 0s 475ms/step - loss: 108492.6953
Epoch 2/2000
1/1 [==============================] - 0s 25ms/step - loss: 108490.0391
Epoch 3/2000
1/1 [==============================] - 0s 27ms/step - loss: 108487.3750
Epoch 4/2000
1/1 [==============================] - 0s 34ms/step - loss: 108484.6953
Epoch 5/2000
1/1 [==============================] - 0s 33ms/step - loss: 108481.9688
Epoch 6/2000
1/1 [==============================] - 0s 28ms/step - loss: 108479.2266
Epoch 7/2000
1/1 [==============================] - 0s 18ms/step - loss: 108476.4375
Epoch 8/2000
1/1 [==============================] - 0s 19ms/step - loss: 108473.6484
Epoch 9/2000
1/1 [==============================] - 0s 34ms/step - loss: 108470.7812
Epoch 10/2000
1/1 [==============================] - 0s 29ms/step - loss: 108467.8984
Epoch 11/2000
1/1 [==============================] - 0s 21ms/step - loss: 108464.9453
Epoch 12/2000
1/1 [==============================] - 0s 23ms/s

1/1 [==============================] - 0s 20ms/step - loss: 103799.4688
Epoch 97/2000
1/1 [==============================] - 0s 19ms/step - loss: 103659.7891
Epoch 98/2000
1/1 [==============================] - 0s 19ms/step - loss: 103517.6875
Epoch 99/2000
1/1 [==============================] - 0s 21ms/step - loss: 103373.1875
Epoch 100/2000
1/1 [==============================] - 0s 21ms/step - loss: 103226.3359
Epoch 101/2000
1/1 [==============================] - 0s 19ms/step - loss: 103077.1797
Epoch 102/2000
1/1 [==============================] - 0s 20ms/step - loss: 102925.8125
Epoch 103/2000
1/1 [==============================] - 0s 17ms/step - loss: 102772.2500
Epoch 104/2000
1/1 [==============================] - 0s 23ms/step - loss: 102616.5938
Epoch 105/2000
1/1 [==============================] - 0s 23ms/step - loss: 102458.9453
Epoch 106/2000
1/1 [==============================] - 0s 15ms/step - loss: 102299.3672
Epoch 107/2000
1/1 [==============================] - 0s 7ms/

1/1 [==============================] - 0s 18ms/step - loss: 92598.3203
Epoch 192/2000
1/1 [==============================] - 0s 21ms/step - loss: 92508.9297
Epoch 193/2000
1/1 [==============================] - 0s 19ms/step - loss: 92418.9609
Epoch 194/2000
1/1 [==============================] - 0s 17ms/step - loss: 92328.3984
Epoch 195/2000
1/1 [==============================] - 0s 18ms/step - loss: 92237.2500
Epoch 196/2000
1/1 [==============================] - 0s 20ms/step - loss: 92145.4766
Epoch 197/2000
1/1 [==============================] - 0s 18ms/step - loss: 92053.1250
Epoch 198/2000
1/1 [==============================] - 0s 19ms/step - loss: 91960.1172
Epoch 199/2000
1/1 [==============================] - 0s 19ms/step - loss: 91866.4766
Epoch 200/2000
1/1 [==============================] - 0s 21ms/step - loss: 91772.2109
Epoch 201/2000
1/1 [==============================] - 0s 18ms/step - loss: 91677.2891
Epoch 202/2000
1/1 [==============================] - 0s 20ms/step - 

1/1 [==============================] - 0s 19ms/step - loss: 82762.5078
Epoch 287/2000
1/1 [==============================] - 0s 23ms/step - loss: 82696.2578
Epoch 288/2000
1/1 [==============================] - 0s 22ms/step - loss: 82632.3125
Epoch 289/2000
1/1 [==============================] - 0s 21ms/step - loss: 82570.6797
Epoch 290/2000
1/1 [==============================] - 0s 21ms/step - loss: 82511.3594
Epoch 291/2000
1/1 [==============================] - 0s 20ms/step - loss: 82454.3672
Epoch 292/2000
1/1 [==============================] - 0s 23ms/step - loss: 82399.6641
Epoch 293/2000
1/1 [==============================] - 0s 21ms/step - loss: 82347.2656
Epoch 294/2000
1/1 [==============================] - 0s 18ms/step - loss: 82297.1484
Epoch 295/2000
1/1 [==============================] - 0s 22ms/step - loss: 82249.2734
Epoch 296/2000
1/1 [==============================] - 0s 21ms/step - loss: 82203.6328
Epoch 297/2000
1/1 [==============================] - 0s 19ms/step - 

1/1 [==============================] - 0s 25ms/step - loss: 81181.5312
Epoch 382/2000
1/1 [==============================] - 0s 22ms/step - loss: 81174.3828
Epoch 383/2000
1/1 [==============================] - 0s 24ms/step - loss: 81167.2344
Epoch 384/2000
1/1 [==============================] - 0s 23ms/step - loss: 81160.0703
Epoch 385/2000
1/1 [==============================] - 0s 21ms/step - loss: 81152.9141
Epoch 386/2000
1/1 [==============================] - 0s 25ms/step - loss: 81145.7344
Epoch 387/2000
1/1 [==============================] - 0s 23ms/step - loss: 81138.5469
Epoch 388/2000
1/1 [==============================] - 0s 23ms/step - loss: 81131.3672
Epoch 389/2000
1/1 [==============================] - 0s 22ms/step - loss: 81124.1641
Epoch 390/2000
1/1 [==============================] - 0s 26ms/step - loss: 81116.9609
Epoch 391/2000
1/1 [==============================] - 0s 21ms/step - loss: 81109.7422
Epoch 392/2000
1/1 [==============================] - 0s 29ms/step - 

1/1 [==============================] - 0s 28ms/step - loss: 19590.7031
Epoch 477/2000
1/1 [==============================] - 0s 18ms/step - loss: 18907.1074
Epoch 478/2000
1/1 [==============================] - 0s 20ms/step - loss: 18250.6230
Epoch 479/2000
1/1 [==============================] - 0s 19ms/step - loss: 17619.7520
Epoch 480/2000
1/1 [==============================] - 0s 20ms/step - loss: 17013.1309
Epoch 481/2000
1/1 [==============================] - 0s 19ms/step - loss: 16429.5781
Epoch 482/2000
1/1 [==============================] - 0s 19ms/step - loss: 15868.0576
Epoch 483/2000
1/1 [==============================] - 0s 20ms/step - loss: 15327.6768
Epoch 484/2000
1/1 [==============================] - 0s 18ms/step - loss: 14807.6260
Epoch 485/2000
1/1 [==============================] - 0s 20ms/step - loss: 14307.2061
Epoch 486/2000
1/1 [==============================] - 0s 19ms/step - loss: 13825.7549
Epoch 487/2000
1/1 [==============================] - 0s 19ms/step - 

1/1 [==============================] - 0s 19ms/step - loss: 3206.8467
Epoch 573/2000
1/1 [==============================] - 0s 20ms/step - loss: 3171.1897
Epoch 574/2000
1/1 [==============================] - 0s 18ms/step - loss: 3136.1484
Epoch 575/2000
1/1 [==============================] - 0s 19ms/step - loss: 3101.7097
Epoch 576/2000
1/1 [==============================] - 0s 19ms/step - loss: 3067.8596
Epoch 577/2000
1/1 [==============================] - 0s 21ms/step - loss: 3034.5879
Epoch 578/2000
1/1 [==============================] - 0s 17ms/step - loss: 3001.8818
Epoch 579/2000
1/1 [==============================] - 0s 18ms/step - loss: 2969.7283
Epoch 580/2000
1/1 [==============================] - 0s 19ms/step - loss: 2938.1179
Epoch 581/2000
1/1 [==============================] - 0s 19ms/step - loss: 2907.0398
Epoch 582/2000
1/1 [==============================] - 0s 19ms/step - loss: 2876.4824
Epoch 583/2000
1/1 [==============================] - 0s 20ms/step - loss: 2846.

1/1 [==============================] - 0s 19ms/step - loss: 1435.5811
Epoch 669/2000
1/1 [==============================] - 0s 20ms/step - loss: 1426.8517
Epoch 670/2000
1/1 [==============================] - 0s 19ms/step - loss: 1418.2223
Epoch 671/2000
1/1 [==============================] - 0s 18ms/step - loss: 1409.6876
Epoch 672/2000
1/1 [==============================] - 0s 18ms/step - loss: 1401.2462
Epoch 673/2000
1/1 [==============================] - 0s 20ms/step - loss: 1392.8973
Epoch 674/2000
1/1 [==============================] - 0s 20ms/step - loss: 1384.6393
Epoch 675/2000
1/1 [==============================] - 0s 19ms/step - loss: 1376.4696
Epoch 676/2000
1/1 [==============================] - 0s 17ms/step - loss: 1368.3872
Epoch 677/2000
1/1 [==============================] - 0s 19ms/step - loss: 1360.3898
Epoch 678/2000
1/1 [==============================] - 0s 19ms/step - loss: 1352.4763
Epoch 679/2000
1/1 [==============================] - 0s 18ms/step - loss: 1344.

1/1 [==============================] - 0s 19ms/step - loss: 861.9614
Epoch 765/2000
1/1 [==============================] - 0s 19ms/step - loss: 857.5540
Epoch 766/2000
1/1 [==============================] - 0s 20ms/step - loss: 853.1635
Epoch 767/2000
1/1 [==============================] - 0s 17ms/step - loss: 848.7905
Epoch 768/2000
1/1 [==============================] - 0s 18ms/step - loss: 844.4348
Epoch 769/2000
1/1 [==============================] - 0s 19ms/step - loss: 840.0957
Epoch 770/2000
1/1 [==============================] - 0s 20ms/step - loss: 835.7734
Epoch 771/2000
1/1 [==============================] - 0s 20ms/step - loss: 831.4660
Epoch 772/2000
1/1 [==============================] - 0s 18ms/step - loss: 827.1768
Epoch 773/2000
1/1 [==============================] - 0s 22ms/step - loss: 822.9025
Epoch 774/2000
1/1 [==============================] - 0s 20ms/step - loss: 818.6450
Epoch 775/2000
1/1 [==============================] - 0s 19ms/step - loss: 814.4019
Epoch 7

1/1 [==============================] - 0s 19ms/step - loss: 498.0677
Epoch 862/2000
1/1 [==============================] - 0s 20ms/step - loss: 494.8997
Epoch 863/2000
1/1 [==============================] - 0s 18ms/step - loss: 491.7422
Epoch 864/2000
1/1 [==============================] - 0s 19ms/step - loss: 488.5968
Epoch 865/2000
1/1 [==============================] - 0s 20ms/step - loss: 485.4618
Epoch 866/2000
1/1 [==============================] - 0s 20ms/step - loss: 482.3383
Epoch 867/2000
1/1 [==============================] - 0s 19ms/step - loss: 479.2267
Epoch 868/2000
1/1 [==============================] - 0s 19ms/step - loss: 476.1264
Epoch 869/2000
1/1 [==============================] - 0s 18ms/step - loss: 473.0378
Epoch 870/2000
1/1 [==============================] - 0s 20ms/step - loss: 469.9596
Epoch 871/2000
1/1 [==============================] - 0s 17ms/step - loss: 466.8933
Epoch 872/2000
1/1 [==============================] - 0s 19ms/step - loss: 463.8380
Epoch 8

1/1 [==============================] - 0s 19ms/step - loss: 244.1833
Epoch 959/2000
1/1 [==============================] - 0s 19ms/step - loss: 242.1316
Epoch 960/2000
1/1 [==============================] - 0s 19ms/step - loss: 240.0913
Epoch 961/2000
1/1 [==============================] - 0s 19ms/step - loss: 238.0625
Epoch 962/2000
1/1 [==============================] - 0s 18ms/step - loss: 236.0449
Epoch 963/2000
1/1 [==============================] - 0s 18ms/step - loss: 234.0393
Epoch 964/2000
1/1 [==============================] - 0s 18ms/step - loss: 232.0440
Epoch 965/2000
1/1 [==============================] - 0s 20ms/step - loss: 230.0610
Epoch 966/2000
1/1 [==============================] - 0s 19ms/step - loss: 228.0889
Epoch 967/2000
1/1 [==============================] - 0s 19ms/step - loss: 226.1284
Epoch 968/2000
1/1 [==============================] - 0s 18ms/step - loss: 224.1790
Epoch 969/2000
1/1 [==============================] - 0s 19ms/step - loss: 222.2408
Epoch 9

1/1 [==============================] - 0s 19ms/step - loss: 95.5472
Epoch 1056/2000
1/1 [==============================] - 0s 19ms/step - loss: 94.5022
Epoch 1057/2000
1/1 [==============================] - 0s 20ms/step - loss: 93.4658
Epoch 1058/2000
1/1 [==============================] - 0s 19ms/step - loss: 92.4384
Epoch 1059/2000
1/1 [==============================] - 0s 20ms/step - loss: 91.4197
Epoch 1060/2000
1/1 [==============================] - 0s 19ms/step - loss: 90.4098
Epoch 1061/2000
1/1 [==============================] - 0s 17ms/step - loss: 89.4085
Epoch 1062/2000
1/1 [==============================] - 0s 18ms/step - loss: 88.4157
Epoch 1063/2000
1/1 [==============================] - 0s 19ms/step - loss: 87.4316
Epoch 1064/2000
1/1 [==============================] - 0s 20ms/step - loss: 86.4559
Epoch 1065/2000
1/1 [==============================] - 0s 18ms/step - loss: 85.4886
Epoch 1066/2000
1/1 [==============================] - 0s 18ms/step - loss: 84.5299
Epoch 10

1/1 [==============================] - 0s 22ms/step - loss: 28.8235
Epoch 1153/2000
1/1 [==============================] - 0s 23ms/step - loss: 28.4302
Epoch 1154/2000
1/1 [==============================] - 0s 21ms/step - loss: 28.0417
Epoch 1155/2000
1/1 [==============================] - 0s 20ms/step - loss: 27.6575
Epoch 1156/2000
1/1 [==============================] - 0s 20ms/step - loss: 27.2779
Epoch 1157/2000
1/1 [==============================] - 0s 21ms/step - loss: 26.9027
Epoch 1158/2000
1/1 [==============================] - 0s 21ms/step - loss: 26.5321
Epoch 1159/2000
1/1 [==============================] - 0s 22ms/step - loss: 26.1658
Epoch 1160/2000
1/1 [==============================] - 0s 21ms/step - loss: 25.8037
Epoch 1161/2000
1/1 [==============================] - 0s 21ms/step - loss: 25.4461
Epoch 1162/2000
1/1 [==============================] - 0s 22ms/step - loss: 25.0928
Epoch 1163/2000
1/1 [==============================] - 0s 21ms/step - loss: 24.7435
Epoch 11

1/1 [==============================] - 0s 19ms/step - loss: 6.6052
Epoch 1251/2000
1/1 [==============================] - 0s 20ms/step - loss: 6.4984
Epoch 1252/2000
1/1 [==============================] - 0s 21ms/step - loss: 6.3932
Epoch 1253/2000
1/1 [==============================] - 0s 19ms/step - loss: 6.2895
Epoch 1254/2000
1/1 [==============================] - 0s 19ms/step - loss: 6.1873
Epoch 1255/2000
1/1 [==============================] - 0s 19ms/step - loss: 6.0868
Epoch 1256/2000
1/1 [==============================] - 0s 19ms/step - loss: 5.9876
Epoch 1257/2000
1/1 [==============================] - 0s 17ms/step - loss: 5.8900
Epoch 1258/2000
1/1 [==============================] - 0s 19ms/step - loss: 5.7937
Epoch 1259/2000
1/1 [==============================] - 0s 18ms/step - loss: 5.6990
Epoch 1260/2000
1/1 [==============================] - 0s 18ms/step - loss: 5.6057
Epoch 1261/2000
1/1 [==============================] - 0s 18ms/step - loss: 5.5137
Epoch 1262/2000
1/1 

1/1 [==============================] - 0s 21ms/step - loss: 1.1991
Epoch 1349/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.1772
Epoch 1350/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.1556
Epoch 1351/2000
1/1 [==============================] - 0s 19ms/step - loss: 1.1344
Epoch 1352/2000
1/1 [==============================] - 0s 19ms/step - loss: 1.1135
Epoch 1353/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.0931
Epoch 1354/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.0730
Epoch 1355/2000
1/1 [==============================] - 0s 17ms/step - loss: 1.0531
Epoch 1356/2000
1/1 [==============================] - 0s 22ms/step - loss: 1.0337
Epoch 1357/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.0146
Epoch 1358/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.9959
Epoch 1359/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.9775
Epoch 1360/2000
1/1 

1/1 [==============================] - 0s 18ms/step - loss: 0.1786
Epoch 1447/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.1750
Epoch 1448/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.1715
Epoch 1449/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.1680
Epoch 1450/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.1647
Epoch 1451/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.1613
Epoch 1452/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.1581
Epoch 1453/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.1549
Epoch 1454/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.1517
Epoch 1455/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.1486
Epoch 1456/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.1456
Epoch 1457/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.1427
Epoch 1458/2000
1/1 

1/1 [==============================] - 0s 18ms/step - loss: 0.0223
Epoch 1545/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.0219
Epoch 1546/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.0214
Epoch 1547/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.0209
Epoch 1548/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.0205
Epoch 1549/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.0200
Epoch 1550/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.0196
Epoch 1551/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.0191
Epoch 1552/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.0187
Epoch 1553/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.0183
Epoch 1554/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.0179
Epoch 1555/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.0175
Epoch 1556/2000
1/1 

1/1 [==============================] - 0s 18ms/step - loss: 0.0024
Epoch 1643/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.0023
Epoch 1644/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.0023
Epoch 1645/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.0022
Epoch 1646/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.0022
Epoch 1647/2000
1/1 [==============================] - 0s 18ms/step - loss: 0.0021
Epoch 1648/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.0021
Epoch 1649/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.0020
Epoch 1650/2000
1/1 [==============================] - 0s 19ms/step - loss: 0.0020
Epoch 1651/2000
1/1 [==============================] - 0s 20ms/step - loss: 0.0019
Epoch 1652/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.0019
Epoch 1653/2000
1/1 [==============================] - 0s 17ms/step - loss: 0.0018
Epoch 1654/2000
1/1 

1/1 [==============================] - 0s 19ms/step - loss: 2.2331e-04
Epoch 1739/2000
1/1 [==============================] - 0s 19ms/step - loss: 2.1736e-04
Epoch 1740/2000
1/1 [==============================] - 0s 17ms/step - loss: 2.1204e-04
Epoch 1741/2000
1/1 [==============================] - 0s 18ms/step - loss: 2.0663e-04
Epoch 1742/2000
1/1 [==============================] - 0s 18ms/step - loss: 2.0139e-04
Epoch 1743/2000
1/1 [==============================] - 0s 19ms/step - loss: 1.9637e-04
Epoch 1744/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.9128e-04
Epoch 1745/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.8647e-04
Epoch 1746/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.8204e-04
Epoch 1747/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.7715e-04
Epoch 1748/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.7279e-04
Epoch 1749/2000
1/1 [==============================] - 0s 1

1/1 [==============================] - 0s 20ms/step - loss: 1.8807e-05
Epoch 1833/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.8350e-05
Epoch 1834/2000
1/1 [==============================] - 0s 21ms/step - loss: 1.7824e-05
Epoch 1835/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.7436e-05
Epoch 1836/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.6876e-05
Epoch 1837/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.6431e-05
Epoch 1838/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.6012e-05
Epoch 1839/2000
1/1 [==============================] - 0s 19ms/step - loss: 1.5587e-05
Epoch 1840/2000
1/1 [==============================] - 0s 19ms/step - loss: 1.5224e-05
Epoch 1841/2000
1/1 [==============================] - 0s 19ms/step - loss: 1.4757e-05
Epoch 1842/2000
1/1 [==============================] - 0s 18ms/step - loss: 1.4367e-05
Epoch 1843/2000
1/1 [==============================] - 0s 1

1/1 [==============================] - 0s 20ms/step - loss: 1.3909e-06
Epoch 1927/2000
1/1 [==============================] - 0s 21ms/step - loss: 1.3340e-06
Epoch 1928/2000
1/1 [==============================] - 0s 22ms/step - loss: 1.3119e-06
Epoch 1929/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.2779e-06
Epoch 1930/2000
1/1 [==============================] - 0s 21ms/step - loss: 1.2536e-06
Epoch 1931/2000
1/1 [==============================] - 0s 21ms/step - loss: 1.2114e-06
Epoch 1932/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.1596e-06
Epoch 1933/2000
1/1 [==============================] - 0s 25ms/step - loss: 1.1363e-06
Epoch 1934/2000
1/1 [==============================] - 0s 27ms/step - loss: 1.1133e-06
Epoch 1935/2000
1/1 [==============================] - 0s 21ms/step - loss: 1.0960e-06
Epoch 1936/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.0674e-06
Epoch 1937/2000
1/1 [==============================] - 0s 2

In [70]:
y_pred = gerador.predict(array)

In [71]:
y_pred

array([[   0.     ,  466.50818,    0.     ,    0.     , 1091.8224 ,
         334.9402 ]], dtype=float32)

In [ ]:
# macarrão, pirarucu, banha, ovo cozido, arroz, chocolate

In [72]:
somando_os_nutrientes_respectivos(y_pred)

array([159.99973328, 138.00079443, 529.99978882])

In [73]:
quantidade_desejada

array([[160., 138., 530.]], dtype=float32)

In [81]:
quantidade_desejada - somando_os_nutrientes_respectivos(y_pred)

array([[ 0.00026672, -0.00079443,  0.00021118]])

In [ ]:
gerador.save('C:/Users/pituc/Downloads/modelos_de_nutrição/gerador_rmsprop_1')

In [ ]:
gerador.save('C:/Users/pituc/Downloads/modelos_de_nutrição/gerador_rmsprop_2')

In [ ]:
gerador.save('C:/Users/pituc/Downloads/modelos_de_nutrição/gerador_rmsprop_3_6_alimentos')

In [85]:
dict(zip( ['proteina', 'gordura', 'carboidrato'] ,somando_os_nutrientes_respectivos(y_pred)))

{'proteina': 159.9997332763672,
 'gordura': 138.00079443359374,
 'carboidrato': 529.9997888183593}

In [84]:
dict(zip( ['macarrão', 'pirarucu', 'banha', 'ovo cozido', 'arroz', 'chocolate'] ,y_pred[0]))

{'macarrão': 0.0,
 'pirarucu': 466.50818,
 'banha': 0.0,
 'ovo cozido': 0.0,
 'arroz': 1091.8224,
 'chocolate': 334.9402}

In [ ]:
array = #shape: (1, quantidade_alimentos), type: np.ndarray, dtype: np.float32
quantidade_desejada = #shape: (1, quantidade_nutrientes), type: np.ndarray, dtype: np.float32
valores_de_certa_comida = #shape: (quantidade_alimentos, quantidade_nutrientes), type= np.ndarray, dtype: np.float32 ou 64
nomes_alimentos = #shape: quantidade_alimentos, type: lista numpy 1 dim, string

In [108]:
valores_de_certa_comida.dtype

dtype('float64')

In [ ]:
# definir um treshold minímino e um treshold maximo em quantidade_dos_alimentos para impedir que um certo alimento não
# ultrapasse a quantidade desejada ou não fique abixo de uma quantidade desejada

In [109]:
class produtor_dieta:
    def __init__(self, array, quantidade_desejada, valores_de_certa_comida, nomes_alimentos):
        self.nomes_alimentos = nomes_alimentos
        self.array = array
        self.quantidade_desejada = quantidade_desejada
        self.valores_de_certa_comida = valores_de_certa_comida 
        self.n_nutrientes = len(quantidade_desejada[0])
            
    def somando_os_nutrientes_respectivos(self, quantidade_dos_alimentos):
        soma_dos_nutrientes_totais = np.zeros(shape= (self.n_nutrientes))
        for n in range(quantidade_dos_alimentos.shape[1]):
            soma_dos_nutrientes_totais = soma_dos_nutrientes_totais + quantidade_dos_alimentos[0][n] * (self.valores_de_certa_comida[n] / 100)
        return soma_dos_nutrientes_totais
    
    def multiplicar_K_por_respectivos_valores_valores(self, y_true, y_pred):
        somas_dos_nutrientes_respectivos = self.somando_os_nutrientes_respectivos(y_pred)
        return K.square(y_true - somas_dos_nutrientes_respectivos)
    
    def fazer_rede(self):
        entrada_gerador = Input(shape= (self.array.shape[1] ,) ) 
        x = entrada_gerador
        n_camadas_gerador = 8
        for n in range(n_camadas_gerador):
            if n < n_camadas_gerador - 1:
                camada = Dense(units= 15, activation= None)
            else:
                camada = Dense(units= self.array.shape[1], activation= 'relu')
            x = camada(x)

        saida_gerador = x
        self.gerador = Model(entrada_gerador, saida_gerador)
        self.gerador.compile(loss= self.multiplicar_K_por_respectivos_valores_valores, optimizer= 'adam' )
    
    def ver_summario(self):
        self.gerador.summary()
    
    def super_ajustar(self):
        self.gerador.fit( self.array , self.quantidade_desejada , epochs= 500 )
        
    def predizer(self):
        self.q_alimento = self.gerador.predict(self.array)
        self.nomes_quantidade = dict(zip(self.nomes_alimentos, self.q_alimento[0]))
        
    def ver_dif_exp_pred(self):
        self.nutricao_total_q_alimento = self.somando_os_nutrientes_respectivos(self.q_alimento)
        print(self.quantidade_desejada - self.nutricao_total_q_alimento)

In [110]:
nomes = ['macarrão', 'pirarucu', 'banha', 'ovo cozido', 'arroz', 'chocolate']
rede = produtor_dieta(array , quantidade_desejada, valores_de_certa_comida, nomes)

In [111]:
rede.fazer_rede()

In [112]:
rede.super_ajustar()

Epoch 1/500
1/1 [==============================] - 0s 292ms/step - loss: 108383.3672
Epoch 2/500
1/1 [==============================] - 0s 82ms/step - loss: 108298.3516
Epoch 3/500
1/1 [==============================] - 0s 32ms/step - loss: 108214.6484
Epoch 4/500
1/1 [==============================] - 0s 32ms/step - loss: 108125.1016
Epoch 5/500
1/1 [==============================] - 0s 29ms/step - loss: 108032.7109
Epoch 6/500
1/1 [==============================] - 0s 32ms/step - loss: 107937.6250
Epoch 7/500
1/1 [==============================] - 0s 35ms/step - loss: 107839.0625
Epoch 8/500
1/1 [==============================] - 0s 40ms/step - loss: 107736.2422
Epoch 9/500
1/1 [==============================] - 0s 33ms/step - loss: 107628.2734
Epoch 10/500
1/1 [==============================] - 0s 23ms/step - loss: 107514.2734
Epoch 11/500
1/1 [==============================] - 0s 22ms/step - loss: 107393.3359
Epoch 12/500
1/1 [==============================] - 0s 23ms/step - loss: 

1/1 [==============================] - 0s 24ms/step - loss: 1877.5913
Epoch 99/500
1/1 [==============================] - 0s 22ms/step - loss: 1715.8882
Epoch 100/500
1/1 [==============================] - 0s 22ms/step - loss: 1565.0524
Epoch 101/500
1/1 [==============================] - 0s 21ms/step - loss: 1436.1221
Epoch 102/500
1/1 [==============================] - 0s 22ms/step - loss: 1336.6050
Epoch 103/500
1/1 [==============================] - 0s 22ms/step - loss: 1269.9396
Epoch 104/500
1/1 [==============================] - 0s 21ms/step - loss: 1235.4215
Epoch 105/500
1/1 [==============================] - 0s 22ms/step - loss: 1228.6144
Epoch 106/500
1/1 [==============================] - 0s 21ms/step - loss: 1242.2523
Epoch 107/500
1/1 [==============================] - 0s 22ms/step - loss: 1267.4869
Epoch 108/500
1/1 [==============================] - 0s 22ms/step - loss: 1295.3077
Epoch 109/500
1/1 [==============================] - 0s 21ms/step - loss: 1317.8701
Epoch 1

1/1 [==============================] - 0s 22ms/step - loss: 571.2162
Epoch 197/500
1/1 [==============================] - 0s 23ms/step - loss: 566.6999
Epoch 198/500
1/1 [==============================] - 0s 21ms/step - loss: 562.2201
Epoch 199/500
1/1 [==============================] - 0s 22ms/step - loss: 557.7745
Epoch 200/500
1/1 [==============================] - 0s 24ms/step - loss: 553.3611
Epoch 201/500
1/1 [==============================] - 0s 21ms/step - loss: 548.9799
Epoch 202/500
1/1 [==============================] - 0s 28ms/step - loss: 544.6298
Epoch 203/500
1/1 [==============================] - 0s 20ms/step - loss: 540.3111
Epoch 204/500
1/1 [==============================] - 0s 21ms/step - loss: 536.0240
Epoch 205/500
1/1 [==============================] - 0s 22ms/step - loss: 531.7680
Epoch 206/500
1/1 [==============================] - 0s 22ms/step - loss: 527.5443
Epoch 207/500
1/1 [==============================] - 0s 21ms/step - loss: 523.3516
Epoch 208/500
1/1 

1/1 [==============================] - 0s 24ms/step - loss: 246.7330
Epoch 295/500
1/1 [==============================] - 0s 22ms/step - loss: 244.3413
Epoch 296/500
1/1 [==============================] - 0s 23ms/step - loss: 241.9644
Epoch 297/500
1/1 [==============================] - 0s 22ms/step - loss: 239.6026
Epoch 298/500
1/1 [==============================] - 0s 26ms/step - loss: 237.2552
Epoch 299/500
1/1 [==============================] - 0s 26ms/step - loss: 234.9229
Epoch 300/500
1/1 [==============================] - 0s 22ms/step - loss: 232.6050
Epoch 301/500
1/1 [==============================] - 0s 24ms/step - loss: 230.3023
Epoch 302/500
1/1 [==============================] - 0s 22ms/step - loss: 228.0140
Epoch 303/500
1/1 [==============================] - 0s 23ms/step - loss: 225.7403
Epoch 304/500
1/1 [==============================] - 0s 23ms/step - loss: 223.4814
Epoch 305/500
1/1 [==============================] - 0s 22ms/step - loss: 221.2367
Epoch 306/500
1/1 

1/1 [==============================] - 0s 25ms/step - loss: 76.5538
Epoch 394/500
1/1 [==============================] - 0s 27ms/step - loss: 75.4646
Epoch 395/500
1/1 [==============================] - 0s 32ms/step - loss: 74.3867
Epoch 396/500
1/1 [==============================] - 0s 29ms/step - loss: 73.3201
Epoch 397/500
1/1 [==============================] - 0s 31ms/step - loss: 72.2642
Epoch 398/500
1/1 [==============================] - 0s 32ms/step - loss: 71.2197
Epoch 399/500
1/1 [==============================] - 0s 31ms/step - loss: 70.1863
Epoch 400/500
1/1 [==============================] - 0s 26ms/step - loss: 69.1637
Epoch 401/500
1/1 [==============================] - 0s 24ms/step - loss: 68.1522
Epoch 402/500
1/1 [==============================] - 0s 29ms/step - loss: 67.1517
Epoch 403/500
1/1 [==============================] - 0s 29ms/step - loss: 66.1617
Epoch 404/500
1/1 [==============================] - 0s 32ms/step - loss: 65.1827
Epoch 405/500
1/1 [===========

1/1 [==============================] - 0s 25ms/step - loss: 13.4946
Epoch 494/500
1/1 [==============================] - 0s 26ms/step - loss: 13.2199
Epoch 495/500
1/1 [==============================] - 0s 23ms/step - loss: 12.9499
Epoch 496/500
1/1 [==============================] - 0s 29ms/step - loss: 12.6848
Epoch 497/500
1/1 [==============================] - 0s 26ms/step - loss: 12.4241
Epoch 498/500
1/1 [==============================] - 0s 22ms/step - loss: 12.1681
Epoch 499/500
1/1 [==============================] - 0s 29ms/step - loss: 11.9165
Epoch 500/500
1/1 [==============================] - 0s 27ms/step - loss: 11.6694


In [113]:
rede.predizer()

In [115]:
rede.nomes_quantidade.values()

dict_values([476.5641, 0.0, 0.0, 630.349, 101.8108, 228.58937])

In [116]:
dict(zip(['macarrão', 'pirarucu', 'banha', 'ovo cozido', 'arroz', 'chocolate'], rede.nomes_quantidade.values()))

{'macarrão': 476.5641,
 'pirarucu': 0.0,
 'banha': 0.0,
 'ovo cozido': 630.349,
 'arroz': 101.8108,
 'chocolate': 228.58937}